shared:
  image: node:18
jobs:
  main:
      requires: [ ~commit ]
      steps:
        - inject: |
           meta set build.warning.message "blocked by some builds, <a href=\"/builds/913516\">913516</a>"
